version: '2'

services:

    web:
      build:
        context: ./nginx
      links:
          - php
      volumes_from:
          - php
      depends_on:
          - php
      ports:
          - 7010:80
          - 7011:8001

    php:
      build: 
        context: ./php
      volumes:
          - ~/Sites:/app
