php:
    build: php
    volumes:
      - /Users/wsmdr/Sites:/app
    external_links:
      - redis_redis_1:redis_redis
nginx:
    build: nginx
    ports:
      - "8001:80"
    links:
      - php
    volumes_from:
      - "php"
