version: '2'

services:

    nginx:
        build:
            context: ./nginx
            args:
                - DEPLOY_WEB_CONFIG=${APPLICATION_NAME}
        depends_on:
            - php
        ports:
            - ${NGINC_PORTS_DEFAULT}:80
            - ${NGINX_HTTPS_PORTS_DEFAULT}:443
        links:
            - php
        volumes_from:
            - php

    php:
        build:
            context: ./php
        volumes:
            - ${ROOT_DIR}:/app
        links:
            - redis
            - mysql
        depends_on:
            - redis
            - mysql

    mysql:
        image: mysql:5.7
        volumes:
            - ${MYSQL_DATA}:/var/lib/mysql
        ports:
            - ${MYSQL_PORTS}:3306
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

    redis:
        image: redis:3.0.7-alpine
        ports:
            - 6379:6379

    redisadmin:
      build:
        context: ./redisadmin
      ports:
        - 8007:80
      volumes_from:
        - php
      links:
        - php
        - redis
      depends_on:
        - php
        - redis

    es:
      build:
        context: ./elasticsearch
      volumes:
        - ${ELASTICSEARCH_DATA}:/usr/share/elasticsearch/data
      ports:
        - 9200:9200
        - 9300:9300
